# Generated by Django 3.1.2 on 2020-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201013_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Broomsticks', 'Broomsticks'), ('Cauldrons', 'Cauldrons')], max_length=20),
        ),
    ]
